name: test_toolkit
version: 0.1.0
homepage: https://github.com/lgunsch/test_toolkit
description: >
  A simple test framework to organize your tests and keep them DRY.
authors:
 - Lewis Gunsch <lewis@gunsch.ca>

dependencies:
  unittest: ">=0.7.0 <0.9.0"
  log4dart: ">=1.4.8 <2.0.0"

